# Generated by Django 4.2.10 on 2024-07-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='Paragraph',
            new_name='paragraph',
        ),
    ]
