# Generated by Django 4.2.10 on 2024-07-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('CreatedAt', models.DateField(auto_now_add=True)),
                ('ModifiedAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
